services:
  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: ./docker/frontend/Dockerfile
    volumes:
    - type: bind
      source: ./frontend
      target: /usr/src/frontend
    #"react-app"の部分がプロジェクト名になる
    # command: sh -c "cd nosy-aunty && yarn start"
    # command: sh -c "yarn start"
    ports:
      - 3000:3000
    stdin_open: true #標準入力をコンテナと紐付ける

  nginx:
    container_name: "nginx"
    build:
      context: ./docker/nginx
    depends_on:
      - backend
    ports:
      - 80:80
    volumes:
      - ./:/src

  backend:
    container_name: "backend"
    build:
      context: ./docker/php
    depends_on:
      - mysql
    ports:
      - 8000:8000
    volumes:
      - ./:/src
      - node_modules:/src/backend/node_modules
      - vendor:/src/backend/vendor
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini

  mysql:
    image: mysql:8.0.33
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --max_allowed_packet=32505856
    container_name: "mysql"
    volumes:
      - ./docker/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=nosy-aunty
    ports:
      - 3306:3306

  redis:
    image: redis:alpine
    container_name: "redis"
    ports:
      - 16379:6379

volumes:
  node_modules:
  vendor: